name: Angular Build and Commit to Dist Folder

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Use the version that your project requires

    - name: Install Dependencies
      run: npm install

    - name: Build Angular Project
      run: npm run build -- --configuration=production  # Updated build command

    - name: Commit and push dist folder
      run: |
        git config --global user.name "DraginSP2"
        git config --global user.email "abhishekparihar1933@gmail.com"
        git add -f dist/  # Force adding the dist/ folder, even if it's ignored by .gitignore
        git commit -m "Add Angular build output" || echo "No changes to commit"
        git push origin main  # Push the changes to the main branch

    # - name: Clean up node_modules and dist from git
    #   run: |
    #     git rm -rf --cached node_modules/
    #     git rm -rf --cached dist/
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
