name: Angular Build and Push

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Set Node.js version to 16

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Run the Angular build command
    - name: Build Angular project
      run: npm run build -- --configuration=production

    # Step 5: Check if dist directory exists and list its contents
    - name: List dist directory contents
      run: |
        if [ -d "dist" ]; then
          echo "Dist folder exists!"
          ls -R dist/
        else
          echo "Dist folder does not exist!"
        fi

    # Step 6: Configure Git user for commit
    - name: Set up Git user
      run: |
        git config --global user.name "DraginSP2"
        git config --global user.email "abhishekparihar1933@gmail.com"

    # Step 7: Commit and push the dist folder to the repository
    - name: Commit and Push dist to Repository
      run: |
        git add dist/
        git commit -m "Add Angular build output"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}

    # Step 8: Clean up orphan processes (Optional)
    - name: Clean up orphan processes
      run: |
        echo "Cleaning up..."
        # Additional cleanup commands can be added here if needed
